### ISSUE TITLE
How can I visit my controller?

### ISSUE THREAD

**Issue by maojindao55** [OpenBuildings/spiderling#13]
How can I visit my controller?

**Comment by hkdobrev** [comment]
Hi @maojindao55, if you are using Kohana, you can use the Kohana driver which would use internal requests and can go through your routing, controllers and actions without firing up a server. Have a look at https://github.com/OpenBuildings/spiderling#driver_kohana.

**Comment by maojindao55** [comment]
@hkdobrev thinks! get it!
