### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by gustiwijayakusuma** [OpenBuildings/spiderling#27]
Hi, i'm try to use your spiderling. After i run it, i get this error message : 
Fatal error: Class 'src\Openbuildings\Spiderling\Page' not found in C:\xampp\htdocs\spiderling-master\test.php on line 4
can you help me with this? i'm so confused why ' use src\Openbuildings\Spiderling\Page; ' is not working

thank you

**Comment by halfer** [comment]
Without more information, this is not easy to answer. It may be that the namespace `use src\Openbuildings\Spiderling\Page` is a problem - `src` is not part of the namespace. You probably wanted `use Openbuildings\Spiderling\Page` instead.

Remember that when you are presenting code/error problems, your readers need to see _detail_. I would recommend that if you have a problem in the future, try to show the relevant part of the code, either in a formatted block, or in a Gist or pasteboard.

**Comment by hkdobrev** [comment]
As @halfer mentioned using PHP namespaces do not depend on the filesystem. You use the namespaces and depend on the autoloader to find them.

```php
use Openbuildings\Spiderling\Page;
```
should work.
