### ISSUE TITLE
General note: PhantomJS project is no longer supported

### ISSUE THREAD

**Issue by halfer** [OpenBuildings/spiderling#31]
It looks like the PhantomJS project will soon be archived, since it has lost its sole maintainer:

https://semaphoreci.com/blog/2018/03/27/phantomjs-is-dead-use-chrome-headless-in-continuous-integration.html

https://github.com/ariya/phantomjs/issues/15344

I guess switching to Selenium and Firefox is the easiest possible change for Spiderling users?

**Comment by hkdobrev** [comment]
Selenium is already supported by Spiderling. I guess anyone else currently using PhantomJS could continue using the latest version. I'd recommend people migrating to more supported tools like Chrome puppeteer and Mink.

**Comment by halfer** [comment]
> Selenium is already supported by Spiderling

Yes, sorry - that's what I meant. I wonder if it will be a drop-in replacement for the `phantomjs` driver? :smile_cat: Ajax waits and other corner cases would be a good test of this!

Puppeteer sounds good, but it's Chrome/Chromium only, so would be no good for folks wanting to be able to switch out the browser.

**Comment by hkdobrev** [comment]
In terms of Spiderling API in PHP code, it's a drop-in replacement. A couple of things to consider - the Selenium server is started differently and Spiderling does not start it automatically. All of the waits for AJAX are not handled in the driver, but in the locators instead so there shouldn't be much difference there. The biggest difference would be the ECMAScript features and JavaScript engine.
