### ISSUE TITLE
Dependency issue: Support for Symfony > 2.3 

### ISSUE THREAD

**Issue by elmariachi111** [OpenBuildings/spiderling#5]
I'm not a composer guru (thanks for workarounds I might be missing besides forking) but I think it's currently not possible to add the dev-master version to a Symfony 2.6 project since spiderling's composer.json depends on css selector 2.3.x but Sf 2.6 comes with a version 2.6.x.  
```` 
 Installation request for symfony/symfony 2.6.0 -> satisfiable by symfony/symfony[v2.6.0].
    - openbuildings/spiderling dev-master requires symfony/css-selector 2.3.* -> satisfiable by symfony/css-selector[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9].
    - don't install symfony/css-selector v2.3.0|don't install symfony/symfony v2.6.0
    ....
````

**Comment by hkdobrev** [comment]
@elmariachi111 It's long overdue, but your problem is now fixed in version [`0.2.24`](https://github.com/OpenBuildings/spiderling/releases/tag/0.2.24) with increased testing of lowest and highest versions and on multiple PHP versions.
