### ISSUE TITLE
How can PhantomJS JavaScript issues best be debugged?

### ISSUE THREAD

**Issue by halfer** [OpenBuildings/spiderling#8]
I'm trying to test a part of my site with the `phantomjs` driver that requires JavaScript, and I can't see any evidence that JavaScript is being run at all. I've modified my code so that an alert box is opened on a jQuery `document.ready()`, and then taken a screenshot programmatically. The screenshot creates fine, the page looks OK, but there is no alert box.

I'm looking at very basic Phantom logs and am not seeing anything of interest:

	port 4725
	Recieved command  POST /url http://localhost:8090/auth?provider=test
	  Executing command  POST /url http://localhost:8090/auth?provider=test
	http://localhost:8090/auth?provider=test success
	Recieved command  POST /elements .//descendant-or-self::*[@id = 'auth-status']
	  Executing command  POST /elements .//descendant-or-self::*[@id = 'auth-status']
	Recieved command  GET /element/0/text 
	  Executing command  GET /element/0/text 
	Recieved command  POST /url http://localhost:8090/report/new
	  Executing command  POST /url http://localhost:8090/report/new
	http://localhost:8090/report/new success
	Recieved command  POST /screenshot /home/jon/Development/Personal/Awooga/webapp/screen.png
	  Executing command  POST /screenshot /home/jon/Development/Personal/Awooga/webapp/screen.png
	Recieved command  POST /url http://localhost:8090/report/new
	  Executing command  POST /url http://localhost:8090/report/new
	http://localhost:8090/report/new success
	Recieved command  POST /elements .//*[((self::input and @type = 'submit') or self::button) and (contains(@title, 'Save') or @id = 'Save' or contains(normalize-space(), 'Save') or descendant::img[contains(@alt, 'Save')] or contains(@value, 'Save') or @name = 'Save')]
	  Executing command  POST /elements .//*[((self::input and @type = 'submit') or self::button) and (contains(@title, 'Save') or @id = 'Save' or contains(normalize-space(), 'Save') or descendant::img[contains(@alt, 'Save')] or contains(@value, 'Save') or @name = 'Save')]
	Recieved command  POST /element/0/click undefined
	  Executing command  POST /element/0/click undefined

I've tried opening the `alert()` outside of jQuery, and that makes no difference.

I've also checked to see if there are any JS issues after the initial opening, thus:

		print_r($this->driver()->javascript_messages());
		print_r($this->driver()->javascript_errors());

However I get an empty array in each case.

<s>Next thing to try, assuming PhantomJs is run in 'GhostDriver' mode, is to see if a custom `--webdriver-loglevel` setting can be provided. Turning this up to 'DEBUG' might yield something.</s> I don't think it runs in GhostDriver mode.

I tried adding `--debug` to the PhantomJS command, it does add a lot of extra lines to the debug output, but nothing obviously of relevance.

I've used this:

		print_r($this->driver()->connection()->get('settings'));

to confirm JavaScript is enabled:

	Array
	(
	    [XSSAuditingEnabled] => 
	    [javascriptCanCloseWindows] => 1
	    [javascriptCanOpenWindows] => 1
	    [javascriptEnabled] => 1
	    [loadImages] => 1
	    [localToRemoteUrlAccessEnabled] => 
	    [userAgent] => Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.7 Safari/534.34
	    [webSecurityEnabled] => 1
	)

So it ought to be working!

If you have any other suggestions, I'd appreciate them.

**Comment by hkdobrev** [comment]
@halfer As far as I know `alert()` and `confirm()` dialogs do not work in PhantomJS.

**Comment by halfer** [comment]
Aha, thanks, that will save me a wild goose chase! I will try another simple test. This may be just an environment thing I'm missing, will update.

**Comment by halfer** [comment]
The problem was on my side - an incorrect selector resulting from an incorrect understanding of `nth-child` compounded by a bug causing something not to show in Webkit. The screenshot feature of Phantom was great in helping to track it down.
